config/routes.rb
Rails.application.routes.draw do
  
  get 'low_stocks/ordered' => 'low_stocks#archived'
  
  get 'low_stocks/history' => 'low_stocks#history'
  
  resources :low_stocks do
    member do
      patch :complete
    end
  end
  
  devise_for :users
  
  get 'home/index' => 'home#index'
  
  get 'treatments/archived' => 'treatments#archived'
  
  resources :treatments do
    member do
      patch :complete
    end
  end
  
  get 'loans/archived' => 'loans#archived'
  
  get 'loans/stock' => 'loans#stock'
  
  resources :loans do
    member do
      patch :complete
    end
  end
  
  get 'parts/all' => 'parts#view', :as => :parts_all
  
  get 'orders/archived' => 'orders#archived'
  
  get 'orders/:printer/parts' => 'orders#printerparts', :as => :parts_by_printer
  
  get 'orders/new' => 'orders#new', :as => :a_new_order
  
  resources :orders do
    member do
      patch :complete
    end
    resources :parts
  end
  resources :parts
  
  get 'region-orders/:region' => 'orders#region', :as => :orders_by_region
  

  root 'loans#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/low_stock.rb
class LowStock < ActiveRecord::Base
    belongs_to :user
end

app/controllers/low_stocks_controller.rb
class LowStocksController < ApplicationController
  before_action :set_low_stock, only: [:show, :edit, :update, :destroy]

  # GET /low_stocks
  # GET /low_stocks.json
  def index
    @low_stocks = LowStock.all
  end

  # GET /low_stocks/1
  # GET /low_stocks/1.json
  def show
  end

  # GET /low_stocks/new
  def new
    @low_stock = LowStock.new
  end

  # GET /low_stocks/1/edit
  def edit
    
  end

  # POST /low_stocks
  # POST /low_stocks.json
  def create
    # Hello bobo! So, your issue was that you weren't setting the user_id when you were creating the @low_stock record
    # You can do that in two ways, you could create the @low_stock like you were doing, and then on a new line have:
    # @low_stock.user = current_user (which you've already specified)
    # or you can do the below, where you have @low_stock = current_user.low_stocks.new instead of @low_stock = LowStock.new
    # I hope you have a wonderful day ok bye lots of love bye
    @low_stock = current_user.low_stocks.new(low_stock_params)

    respond_to do |format|
      if @low_stock.save
        format.html { redirect_to low_stocks_path, notice: 'Low stock was successfully created.' }
        format.json { render :show, status: :created, location: @low_stock }
      else
        format.html { render :new }
        format.json { render json: @low_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /low_stocks/1
  # PATCH/PUT /low_stocks/1.json
  def update
    
    respond_to do |format|
      if @low_stock.update(low_stock_params)
        format.html { redirect_to low_stocks_path, notice: 'Low stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @low_stock }
      else
        format.html { render :edit }
        format.json { render json: @low_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /low_stocks/1
  # DELETE /low_stocks/1.json
  def destroy
    @low_stock.destroy
    respond_to do |format|
      format.html { redirect_to low_stocks_url, notice: 'Low stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def complete
    @low_stock = LowStock.find(params[:id])
    time = Time.now
    @low_stock.update_attribute(:completed_at, time.to_formatted_s(:short))
    redirect_to low_stocks_path, notice: "Part placed on order"
  end
  
  def archived
    @low_stocks = LowStock.all
  end  
  
  def history
    @low_stocks = LowStock.all
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_low_stock
      @low_stock = LowStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def low_stock_params
      params.require(:low_stock).permit(:part_number, :description, :quantity_in_stock, :quantity_required, :user_id, :due_date)
    end
end

app/helpers/low_stocks_helper.rb
module LowStocksHelper
end

app/views/low_stocks/_form.html.erb
<%= form_for(@low_stock) do |f| %>
  <% if @low_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@low_stock.errors.count, "error") %> prohibited this low_stock from being saved:</h2>

      <ul>
      <% @low_stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "col-md-6">
    <% user_name = current_user.email.chomp("@opendate.co.uk").gsub(".", " ").split(" ")[0] %>
    
    <%= f.label :part_number %></br>
    <%= f.text_field :part_number %></br>
    
    <%= f.label :description %></br>
    <%= f.text_field :description %></br>
    
    <%= f.label :quantity_in_stock %></br>
    <%= f.text_field :quantity_in_stock %></br>
    
    <%= f.label :quantity_required %></br>
    <%= f.text_field :quantity_required %></br>
    
    <%= f.label :user_id, "Entered by" %></br>
    <%= f.text_field :user_id, :value => user_name.camelize, :readonly => true %></br>
  
  
    <div class="actions">
      <%= f.submit "Confirm", class: "btn btn-primary" %>
    </div>
    
  </div>


<% end %>

app/views/low_stocks/archived.html.erb
<% @title = "OD Dbase - Processed parts" %>

<p id="notice"><%= notice %></p>

<div class = "title-spacing">
  <h2>Ordered parts</h2>
</div>

<%= link_to 'Back to outstanding', low_stocks_path, class: "btn btn-primary" %>

<table class = "table">
  <thead>
    <tr>
      <th>Part Number</th>
      <th>Description</th>
      <th>Stock Qty</th>
      <th>Required Qty</th>
      <th>Entered By</th>
      <th>Date Ordered</th>
      <th>Due Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @low_stocks.each do |low_stock| %>
      <% if low_stock.due_date.present? && low_stock.completed_at.blank? %>
        <tr>
          <td><%= low_stock.part_number %></td>
          <td><%= low_stock.description %></td>
          <td><%= low_stock.quantity_in_stock %></td>
          <td><%= low_stock.quantity_required %></td>
          <td><%= low_stock.user.email.chomp("@opendate.co.uk").gsub(".", " ").split(" ")[0].camelize %></td>
          <td><%= low_stock.updated_at.strftime("%d/%m/%y") %></td>
          <td><%= low_stock.due_date %></td>
          <td><%= link_to 'Received', complete_low_stock_path(low_stock), method: :patch, class: "link_to" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/low_stocks/edit.html.erb
<% @title = "OD Dbase - Edit low stock item" %>

<div class = "title-spacing">
    <h2>Editing Low Stock</h2>
</div>

<%= render 'form' %>

app/views/low_stocks/history.html.erb
<% @title = "OD Dbase - Low stock history" %>

<p id="notice"><%= notice %></p>

<div class = "title-spacing">
  <h2>Low stock history</h2>
</div>

<%= link_to 'Parts outstanding', low_stocks_path, class: "btn btn-primary" %>

<table class = "table">
  <thead>
    <tr>
      <th>Part number</th>
      <th>Description</th>
      <th>Quantity requested</th>
      <th>Date ordered</th>
      <th>Due date</th>
      <th>Received</th>
    </tr>
  </thead>

  <tbody>
    <% @low_stocks.each do |low_stock| %>
        <% if low_stock.completed_at.present? %>
            <tr>
              <td><%= low_stock.part_number %></td>
              <td><%= low_stock.description %></td>
              <td><%= low_stock.quantity_required %></td>
              <td><%= low_stock.updated_at.strftime("%d/%m/%y") %></td>
              <td><%= low_stock.due_date %></td>
              <td><%= low_stock.completed_at.to_date.strftime("%d/%m/%y") %></td>
            </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/low_stocks/index.html.erb
<% @title = "OD Dbase - Low stock" %>

<p id="notice"><%= notice %></p>

<div class = "title-spacing">
  <h2>Low stock</h2>
</div>

<% if current_user %>
<%= link_to 'New low stock entry', new_low_stock_path, class: "btn btn-primary" %><%= link_to 'Parts on order', low_stocks_ordered_path, class: "btn btn-primary" %><%= link_to 'History', low_stocks_history_path, class: "btn btn-primary" %>
<% end %>

<table class = "table">
  <thead>
    <tr>
      <th>Part Number</th>
      <th>Description</th>
      <th>Stock Qty</th>
      <th>Required Qty</th>
      <th>Entered By</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @low_stocks.each do |low_stock| %>
      <% if low_stock.due_date.blank? && low_stock.completed_at.blank? %>
        <tr>
          <td><%= low_stock.part_number %></td>
          <td><%= low_stock.description %></td>
          <td><%= low_stock.quantity_in_stock %></td>
          <td><%= low_stock.quantity_required %></td>
          <td><%= low_stock.user.email.chomp("@opendate.co.uk").gsub(".", " ").split(" ")[0].camelize %></td>
<% if false %>
  <% if current_user == low_stock.user %>
  <td><%= link_to 'Edit', edit_low_stock_path(low_stock), class: "link_to" %></td>
  <% else %>
  <td></td>
  <% end %>
<% end %>
          <td>
            <%= form_for(low_stock) do |f| %>
              <%= f.text_field :due_date, :placeholder => "Due date/cancel" %>
              <%= f.submit "On order", method: :post %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/low_stocks/new.html.erb
<% @title = "OD Dbase - New low stock item" %>

<div class = "title-spacing">
    <h2>New Low Stock Entry</h2>
</div>

<%= render 'form' %>

app/views/low_stocks/ordered.html.erb
<p id="notice"><%= notice %></p>

<h2>Parts on order</h2>

<%= link_to 'Parts outstanding', low_stocks_path, class: "btn btn-primary" %>

<table class = "table">
  <thead>
    <tr>
      <th>Part number</th>
      <th>Description</th>
      <th>Quantity requested</th>
      <th>Date ordered</th>
    </tr>
  </thead>

  <tbody>
    <% @low_stock.each do |low_stock| %>
        <% if low_stock.completed_at.present? %>
            <tr>
              <td><%= low_stock.part_number %></td>
              <td><%= low_stock.description %></td>
              <td><%= low_stock.quantity_required %></td>
              <td><%= low_stock.completed_at %></td>
            </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/low_stocks/show.html.erb
<% @title = "OD Dbase - Low stock item details" %>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_low_stock_path(@low_stock) %> |
<%= link_to 'Back', low_stocks_path %>