config/routes.rb
Rails.application.routes.draw do
  
  get 'low_stocks/ordered' => 'low_stocks#archived'
  
  get 'low_stocks/history' => 'low_stocks#history'
  
  resources :low_stocks do
    member do
      patch :complete
    end
  end
  
  devise_for :users
  
  get 'home/index' => 'home#index'
  
  get 'treatments/archived' => 'treatments#archived'
  
  resources :treatments do
    member do
      patch :complete
    end
  end
  
  get 'loans/archived' => 'loans#archived'
  
  get 'loans/stock' => 'loans#stock'
  
  resources :loans do
    member do
      patch :complete
    end
  end
  
  get 'parts/all' => 'parts#view', :as => :parts_all
  
  get 'orders/archived' => 'orders#archived'
  
  get 'orders/:printer/parts' => 'orders#printerparts', :as => :parts_by_printer
  
  get 'orders/new' => 'orders#new', :as => :a_new_order
  
  resources :orders do
    member do
      patch :complete
    end
    resources :parts
  end
  resources :parts
  
  get 'region-orders/:region' => 'orders#region', :as => :orders_by_region
  

  root 'loans#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index
        @treatments = Treatment.all.reorder("completed_at")
        @treatments_outstanding = Treatment.where(completed_at: nil).order("date_due_back")
        @orders = Order.all.reorder("completed_at")
        @orders_outstanding = Order.where(completed_at: nil).where.not(due_date: nil).order("due_date")
    end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% @title = "OD Dbase - Home" %>

<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">The Latest - 
                <small>The most recent ins and outs</small>
            </h1>
        </div>
    </div>
    
    <div class="row">

        <div class="col-md-6 portfolio-item">
            <h3>
                <%= link_to 'Treatments', treatments_archived_path, class: "link_to" %>
            </h3>
            <p>Fresh in on anodising and plating</p>
             <table class = "table">
              <thead>
                <tr>
                  <th>Part Number</th>
                  <th>Description</th>
                  <th>Quantity</th>
                </tr>
              </thead>
            
              <tbody>
                <% @treatments.limit(5).each do |treatment| %>
                  <% if treatment.completed_at.present? %>
                    <tr>
                      <td><%= treatment.part_number %></td>
                      <td><%= treatment.description %></td>
                      <td><%= treatment.quantity %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>

        </div>
        <div class="col-md-6 portfolio-item">
            <h3>
                <%= link_to 'Shipments', orders_archived_path, class: "link_to" %>
            </h3>
            <p>Recent printers out the door</p>
            <table class = "table">
              <thead>
                <tr>
                  <th>Customer</th>
                  <th>Printer</th>
                  <th>Quantity</th>
                </tr>
              </thead>
            
              <tbody>
                <% @orders.limit(5).each do |order| %>
                    <% if order.completed_at.present? %>
                      <tr>
                        <td><%= order.customer %></td>
                        <td><%= order.printer %></td>
                        <td><%= order.quantity %></td>
                      </tr>
                    <% end %>
                <% end %>
              </tbody>
            </table>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Next Up - 
              <small>What we're expecting to come and go next</small>
            </h1>
            
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <h3>
                <%= link_to 'Treatments', treatments_path, class: "link_to" %>
            </h3>
            <p>Next bits due back on anodising and plating</p>
            <table class = "table">
              <thead>
                <tr>
                  <th>Part ref</th>
                  <th>Description</th>
                  <th>Quantity</th>
                  <th>Supplier</th>
                  <th>Due in</th>
                </tr>
              </thead>
            
              <tbody>
                <% @treatments_outstanding.limit(5).each do |treatment| %>
                  
                    <tr>
                      <td><%= treatment.part_number %></td>
                      <td><%= treatment.description %></td>
                      <td><%= treatment.quantity %></td>
                      <td><%= treatment.supplier %></td>
                      <td><%= treatment.date_due_back %></td>
                    </tr>
                  
                <% end %>
              </tbody>
            </table>
        </div>
        <div class="col-md-6 portfolio-item">
            <h3>
                <%= link_to 'Shipments', orders_path, class: "link_to" %>
            </h3>
            <p>Printers next due up for despatch</p>
            <table class = "table">
              <thead>
                <tr>
                  <th>Order Number</th>
                  <th>Customer</th>
                  <th>Printer</th>
                  <th>Quantity</th>
                  <th>Due out</th>
                </tr>
              </thead>
            
              <tbody>
                <% @orders_outstanding.limit(5).each do |order| %>
                  
                    <tr>
                      <td><%= order.order_number %></td>
                      <td><%= order.customer %></td>
                      <td><%= order.printer %></td>
                      <td><%= order.quantity %></td>
                      <td><%= order.due_date %></td>
                    </tr>
                  
                <% end %>
              </tbody>
            </table>
        </div>
    </div>
</div>