config/routes.rb
Rails.application.routes.draw do
  
  get 'low_stocks/ordered' => 'low_stocks#archived'
  
  get 'low_stocks/history' => 'low_stocks#history'
  
  resources :low_stocks do
    member do
      patch :complete
    end
  end
  
  devise_for :users
  
  get 'home/index' => 'home#index'
  
  get 'treatments/archived' => 'treatments#archived'
  
  resources :treatments do
    member do
      patch :complete
    end
  end
  
  get 'loans/archived' => 'loans#archived'
  
  get 'loans/stock' => 'loans#stock'
  
  resources :loans do
    member do
      patch :complete
    end
  end
  
  get 'parts/all' => 'parts#view', :as => :parts_all
  
  get 'orders/archived' => 'orders#archived'
  
  get 'orders/:printer/parts' => 'orders#printerparts', :as => :parts_by_printer
  
  get 'orders/new' => 'orders#new', :as => :a_new_order
  
  resources :orders do
    member do
      patch :complete
    end
    resources :parts
  end
  resources :parts
  
  get 'region-orders/:region' => 'orders#region', :as => :orders_by_region
  

  root 'loans#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/order.rb
class Order < ActiveRecord::Base
    
    has_many :parts, dependent: :destroy
    has_many :printers
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all.reorder(:printer, :due_date)
  end

  def show
    
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def region
    @orders = Order.where("region = ?", params[:region]).reorder(:due_date, :printer)
  end
  
  def printerparts
    @orders = Order.where("printer = ?", params[:printer])
  end
  
  def complete
    @order = Order.find(params[:id])
    time = Time.now
    @order.update_attribute(:completed_at, time.to_formatted_s(:short))
    redirect_to orders_path, notice: "Order archived as shipped"
  end
  
  def archived
    @orders = Order.all
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end
    
    def order_params
      params.require(:order).permit(:customer, :order_number, :order_date, :due_date, :region, :printer, :quantity, :status, :notes)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class = "jumbotron">
    
    <%= f.label :order_number %></br>
    <%= f.text_field :order_number %></br>
    
    <%= f.label :customer %></br>
    <%= f.text_field :customer %></br>
    
    <%= f.label :region %></br>
    <%= f.select :region, Region.all.map { |f| f.region } %></br>
    
    <%= f.label :printer %></br>
    <%= f.select :printer, Printer.all.map { |f| f.name } %></br>
    
    <%= f.label :quantity %></br>
    <%= f.text_field :quantity %></br>
    
    <%= f.label :status %></br>
    <%= f.text_field :status %></br>
    
    <%= f.label :order_date %></br>
    <%= f.text_field :order_date, placeholder: 'dd/mm/yy' %></br>
    
    <%= f.label :due_date %></br>
    <%= f.text_field :due_date, placeholder: 'dd/mm/yy' %></br>
    
    <%= f.label :notes %></br>
    <%= f.text_area :notes %></br>
    
    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
    
  </div>


<% end %>

app/views/orders/archived.html.erb
<% @title = "OD Dbase - Shipped orders" %>

<p id="notice"><%= notice %></p>

<div class = "title-spacing">
  <h2>Shipped Orders</h2>
</div>

<%= link_to 'Outstanding Orders', orders_path, class: "btn btn-primary" %>

<table class = "table">
  <thead>
    <tr>
      <th>Order Number</th>
      <th>Customer</th>
      <th>Printer</th>
      <th>Quantity</th>
      <th>Order Date</th>
      <th>Shipped Date</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
        <% if order.completed_at.present? %>
          <tr>
            <td><%= order.order_number %></td>
            <td><%= order.customer %></td>
            <td><%= order.printer %></td>
            <td><%= order.quantity %></td>
            <td><%= order.order_date %></td>
            <td><%= order.completed_at %></td>
            <td><%= order.notes %></td>
          </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

app/views/orders/bycustomer.html.erb
<% @title = "OD Dbase - Outstanding orders" %>

<p id="notice"><%= notice %></p>

<div class = "title-spacing">
  <h2>Outstanding Orders for <%= @order.customer %></h2>
</div>

<%= link_to 'New Order', new_order_path, class: "btn btn-primary" %>

<table class = "table">
  <thead>
    <tr>
      <th>Order Number</th>
      <th>Customer</th>
      <th>Region</th>
      <th>Printer</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Order Date</th>
      <th>Due Date</th>
      <th>Parts Remaining</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.order_number, order %></td>
        <td><%= order.customer %></td>
        <td><%= order.region %></td>
        <td><%= order.printer %></td>
        <td><%= order.quantity %></td>
        <td><%= order.status %></td>
        <td><%= order.order_date %></td>
        <td><%= order.due_date %></td>
        <td><%= order.parts.count %></td>
        <td><%= link_to 'Edit order', edit_order_path(order), class: "link_to" %></td>
        <td><%= link_to 'Mark complete', order, method: :delete, data: { confirm: 'Are you sure?' }, class: "link_to" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/edit.html.erb
<% @title = "OD Dbase - Edit order" %>

<div class = "title-spacing">
    <h2>Editing Order</h2>
</div>

<%= render 'form' %>

app/views/orders/index.html.erb
<% @title = "OD Dbase - Outstanding orders" %>

<p id="notice"><%= notice %></p>

<div class = "title-spacing">
  <h2>Outstanding Orders</h2>
</div>

<%= link_to 'New Order', new_order_path, class: "btn btn-primary" %>
<%= link_to 'Shipped Orders', orders_archived_path, class: "btn btn-primary" %>

<table class = "table">
  <thead>
    <tr>
      <th>Order Number</th>
      <th>Customer</th>
      <th>Printer</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Order Date</th>
      <th>Due Date</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <% if order.completed_at.blank? %>
        <tr>
          <td><%= order.order_number %></td>
          <td><%= order.customer %></td>
          <td><%= order.printer %></td>
          <td><%= order.quantity %></td>
          <td><%= order.status %></td>
          <td><%= order.order_date %></td>
          <td><%= order.due_date %></td>
          <td><%= link_to 'Edit order', edit_order_path(order), class: "link_to" %></td>
          
          <td>
            <%= form_for(order) do |f| %>
              <%= f.text_field :completed_at, :placeholder => "dd/mm/yy" %>
              <%= f.submit "Shipped", method: :post %>
            <% end %>
          </td>
          
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<% @title = "OD Dbase - New order" %>

<div class = "title-spacing">
    <h2>New Order</h2>
</div>

<%= render 'form' %>

app/views/orders/printerparts.html.erb
<% @title = "OD Dbase - Outstanding parts" %>

<div class = "title-spacing">
    <h2>Outstanding parts</h2>
</div>

<table class = "table">
    <thead>
        <tr>
            <th>Part number</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Supplier</th>
            <th></th>
        </tr>
    </thead>

    
    <tbody>
        <% @orders.each do |order| %>
            <% order.parts.each do |part| %>
                <tr>    
                    <td><%= part.part_number %></td>
                    <td><%= part.description %></td>
                    <td><%= part.quantity %></td>
                    <td><%= part.supplier %></td>
                    <td><%= link_to 'Remove from list', part_path(part), method: :delete, data: { confirm: 'Are you sure?' }, class: "link_to" %></td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
    


</table>

app/views/orders/region.html.erb
<% @title = "OD Dbase - Outstanding orders" %>

<p id="notice"><%= notice %></p>

<div class = "title-spacing">
  <h2>Outstanding Orders</h2>
</div>

<%= link_to 'New Order', new_order_path, class: "btn btn-primary" %>


<table class = "table">
  <thead>
    <tr>
      <th>Order Number</th>
      <th>Customer</th>
      <th>Printer</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Order Date</th>
      <th>Due Date</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <% if order.completed_at.blank? %>
        <tr>
          <td><%= order.order_number %></td>
          <td><%= order.customer %></td>
          <td><%= order.printer %></td>
          <td><%= order.quantity %></td>
          <td><%= order.status %></td>
          <td><%= order.order_date %></td>
          <td><%= order.due_date %></td>
          <td><%= link_to 'Edit order', edit_order_path(order), class: "link_to" %></td>
          <td><%= link_to 'Shipped', complete_order_path(order), method: :patch, class: "link_to" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/orders/regionuk.html.erb
<% @title = "OD Dbase - Outstanding UK orders" %>

<p id="notice"><%= notice %></p>

<h2>Outstanding UK Orders</h2>

<%= link_to 'New Order', new_order_path, class: "btn btn-primary" %>

<table class = "table">
  <thead>
    <tr>
      <th>Order Number</th>
      <th>Customer</th>
      <th>Printer</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Order Date</th>
      <th>Due Date</th>
      <th>Parts Remaining</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.order_number, order %></td>
        <td><%= link_to order.customer, order %></td>
        <td><%= order.printer %></td>
        <td><%= order.quantity %></td>
        <td><%= order.status %></td>
        <td><%= order.order_date %></td>
        <td><%= order.due_date %></td>
        <td><%= order.parts.count %></td>
        <td><%= link_to 'Edit order', edit_order_path(order) %></td>
        <td><%= link_to 'Mark complete', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<% @title = "OD Dbase - Order details" %>

<p id="notice"><%= notice %></p>

<div class = "title-spacing">
    <h2>Order details</h2>
</div>

<ul class = "list-group">
    <li><strong>Customer:</strong>           <%= @order.customer %>, <%= @order.region %></li>
    <li><strong>Order number:</strong>       <%= @order.order_number %></li>
    <li><strong>Printer:</strong>            <%= @order.quantity %> x <%= @order.printer %></li>
    <li><strong>Status:</strong>             <%= @order.status %></li>
    <li><strong>Order date:</strong>         <%= @order.order_date %></li>
    <li><strong>Due date:</strong>           <%= @order.due_date %></li>
    <li><strong>Notes:</strong>              <%= @order.notes %></li>
</ul>

<h3>Parts needed for completion</h3>

<%= link_to 'Add a new part', new_order_part_path(@order), class: "btn btn-primary" %>

<table class = "table">
    <tr>
        <th>Part number</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Supplier</th>
    </tr>
    
    <% @order.parts.each do |f| %>
    
    <tr>
        <td><%= f.part_number %></td>
        <td><%= f.description %></td>
        <td><%= f.quantity %></td>
        <td><%= f.supplier %></td>
    </tr>
    
    <% end %>
    
</table>