config/routes.rb
Rails.application.routes.draw do
  
  get 'low_stocks/ordered' => 'low_stocks#archived'
  
  get 'low_stocks/history' => 'low_stocks#history'
  
  resources :low_stocks do
    member do
      patch :complete
    end
  end
  
  devise_for :users
  
  get 'home/index' => 'home#index'
  
  get 'treatments/archived' => 'treatments#archived'
  
  resources :treatments do
    member do
      patch :complete
    end
  end
  
  get 'loans/archived' => 'loans#archived'
  
  get 'loans/stock' => 'loans#stock'
  
  resources :loans do
    member do
      patch :complete
    end
  end
  
  get 'parts/all' => 'parts#view', :as => :parts_all
  
  get 'orders/archived' => 'orders#archived'
  
  get 'orders/:printer/parts' => 'orders#printerparts', :as => :parts_by_printer
  
  get 'orders/new' => 'orders#new', :as => :a_new_order
  
  resources :orders do
    member do
      patch :complete
    end
    resources :parts
  end
  resources :parts
  
  get 'region-orders/:region' => 'orders#region', :as => :orders_by_region
  

  root 'loans#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,500' rel='stylesheet' type='text/css'>
</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to root_path do %>
        <%= image_tag "logo2.png", class: "logo-image" %>
      <% end %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <li>
          <% if current_user %>
            <p class = "login">Logged in as <%= current_user.email.chomp("@opendate.co.uk").gsub(".", " ").split(" ")[0].camelize %></p>
          <% end %>
        </li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete if current_user %></li>
        
        <% if false %>
          <li class = "link_to"><%= link_to 'Low stock', low_stocks_path %></li>
          <li class = "link_to"><%= link_to 'Treatments', treatments_path, class: "link_to" %></li>
        <% end %>
        <li class = "link_to"><%= link_to 'Loans', loans_path, class: "link_to" %></li>
        
<% if false %> 
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Outstanding parts<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>Thermal</li>
            <li><%= link_to '53E', parts_by_printer_path(:printer => '53E') %></li>
            <li><%= link_to '53S', parts_by_printer_path(:printer => '53S') %></li>
            <li><%= link_to '53M', parts_by_printer_path(:printer => '53M') %></li>
            <li><%= link_to '53L', parts_by_printer_path(:printer => '53L') %></li>
            <li><%= link_to '53CR', parts_by_printer_path(:printer => '53CR') %></li>
            <li><%= link_to '53CL', parts_by_printer_path(:printer => '53CL') %></li>
            <li><%= link_to '107S', parts_by_printer_path(:printer => '107S') %></li>
            <li><%= link_to '107M', parts_by_printer_path(:printer => '107M') %></li>
            <li><%= link_to '107L', parts_by_printer_path(:printer => '107L') %></li>
            <li><%= link_to '107CR', parts_by_printer_path(:printer => '107CR') %></li>
            <li><%= link_to '107CL', parts_by_printer_path(:printer => '107CL') %></li>
            <li><%= link_to 'iQ', parts_by_printer_path(:printer => 'iQ') %></li>
            <li role="separator" class="divider"></li>
            <li>Hot Foil</li>
            <li><%= link_to 'Eurocode 150', parts_by_printer_path(:printer => 'Eurocode 150') %></li>
            <li><%= link_to 'Eurocode 180', parts_by_printer_path(:printer => 'Eurocode 180') %></li>
            <li><%= link_to 'Eurocode 300', parts_by_printer_path(:printer => 'Eurocode 300') %></li>
            <li><%= link_to 'Printmaster', parts_by_printer_path(:printer => 'Printmaster') %></li>
            <li><%= link_to 'Printmaster 1000', parts_by_printer_path(:printer => 'Printmaster 1000') %></li>
            <li><%= link_to 'Printmaster Plus', parts_by_printer_path(:printer => 'Printmaster Plus') %></li>
            <li><%= link_to 'E-Coder', parts_by_printer_path(:printer => 'E-Coder') %></li>
            <li><%= link_to 'Sprint Major', parts_by_printer_path(:printer => 'Sprint Major') %></li>
            <li><%= link_to 'Sprint', parts_by_printer_path(:printer => 'Sprint') %></li>
            <li role="separator" class="divider"></li>
            <li>Carton Feeder</li>
            <li><%= link_to 'MC-810 Carton Feeder', parts_by_printer_path(:printer => 'MC-810 Carton Feeder') %></li>
            <li role="separator" class="divider"></li>
            <li>Debosser</li>
            <li><%= link_to 'Hot Debosser', parts_by_printer_path(:printer => 'Hot Debosser') %></li>
            <li><%= link_to 'Cold Debosser', parts_by_printer_path(:printer => 'Cold Debosser') %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'All', parts_all_path %></li>
          </ul>
        </li>


        <li class="dropdown link_to">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Outstanding orders<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'USA', orders_by_region_path(:region => 'USA') %></li>
            <li><%= link_to 'France', orders_by_region_path(:region => 'France') %></li>
            <li><%= link_to 'Germany', orders_by_region_path(:region => 'Germany') %></li>
            <li><%= link_to 'UK', orders_by_region_path(:region => 'UK') %></li>
            <li><%= link_to 'Export', orders_by_region_path(:region => 'Export') %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'All', orders_path %></li>
          </ul>
        </li>
<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>